### PR TITLE
add base support of Mediainfo OtherStream

### PR DESCRIPTION
**Pull request by ShockwaveNN**
Fix Error 'Uncaught exception: bad stream type: "Other"'
May influence issue #3

### CODE REVIEW

**Comment by azelenets** [comment]
It is really needs, coz sometimes MediaInfo fail to get info from file with stream type, :other

**Comment by ShockwaveNN** [comment]
@azelenets I think this project is completly dead, I tryed to contact author in 2014 year and he never answered.

**Comment by azelenets** [comment]
@ShockwaveNN That's bad - monkey patch give me all. :) Thanks for this solution!

**Comment by NorseGaud** [comment]
Closing due to age, but will include it in 0.8.0 (maybe a week or two until release)

**Pull request closed without merging**
