### PR TITLE
allow use of URL in filename

### PR DESCRIPTION
**Pull request by DaKaZ**
This patch allows a user to supply a URI for media info to parse

### CODE REVIEW

**Comment by NorseGaud** [comment]
Including in 1.0.0 which will be released soon. Thank you!

**Comment by ryanto** [comment]
Any update on this?

**Comment by NorseGaud** [comment]
Finalizing new duration standardization code. I've been a little overworked at my full time, so haven't made any progress for ~6 days. I'll be able to kick it back into gear tomorrow now that things are settling.

**Comment by ryanto** [comment]
Awesome! I'm excited for this feature.

If you have an issues/bugfixes you'd like me to take a look at feel free to ping me.

**Comment by NorseGaud** [comment]
Awesome, thanks! I was able to finish it up (it was less work than I thought lol) and submitted the pull request to Seth. I shot him an email since he's not active on here, so it may be a few more days until he can get around to the review.

**Pull request closed without merging**
